use_directory_urls: true
site_name: Zooza Documentation
site_url: https://docs.zooza.online/
site_dir: dist
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - content.metadata
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - mermaid2
  - swagger-ui-tag
nav:
  - Home: index.md
  - Concepts: concepts.md
  - Quickstart: quickstart.md
  - Widgets:
      - Overview: widgets/index.md
      - Registration widget: widgets/registration-widget.md
      - Calendar widget: widgets/calendar-widget.md
      - Map widget: widgets/map-widget.md
      - Profile widget: widgets/profile-widget.md
      - Video widget: widgets/video-widget.md
      - Checkout widget: widgets/checkout-widget.md
  - API reference:
      - Overview: api/index.md
      - Authentication: api/authentication.md
      - Endpoints: api/endpoints.md
      - Error handling: api/errors.md
  - Enums reference: enums.md
extra:
  robots: "robots.txt"
